[programs.localnet]
defender = "5Nh6B8mvMuHkn9bgB2Sh59zypRLVcHNCe5bBQyE1b2Ey"

[programs.devnet]
defender = "5Nh6B8mvMuHkn9bgB2Sh59zypRLVcHNCe5bBQyE1b2Ey"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/williamwzeng/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
